version: "3"

services:
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "./predefined:/code/predefined"
      - "./settings.yaml:/code/settings.yaml"
    environment:
      - TZ=Europe/Moscow
    env_file: .env
    networks:
      - default
      - music-room

  db:
    image: "postgres:15.3"
    restart: always
    command: postgres -c synchronous_commit=off
    volumes:
      - "postgres:/var/lib/postgresql/data"
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:

networks:
  music-room:
    external: true
    name: music-room
