version: "3"

services:
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
     - "./src/repositories/predefined:/code/src/repositories/predefined"
    env_file: .env.local

  db:
    image: "postgres:15.3"
    restart: always
    command: postgres -c synchronous_commit=off
    volumes:
      - "postgres:/var/lib/postgresql/data"
    env_file: .env.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
    postgres:
