[tool.poetry]
name = "innohassle-events"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10,<3.12"
sqlalchemy = {extras = ["asyncpg"], version = "^2.0.17"}
aiohttp = "^3.8.4"
asyncpg = { version = "^0.27.0", allow-prereleases = true }
alembic = "^1.10.2"
pydantic = {extras = ["dotenv"], version = "^1.10.7"}
fastapi = "^0.97.0"
uvicorn = "^0.22.0"
authlib = "^1.2.0"
requests = "^2.31.0"
httpx = "^0.24.1"
itsdangerous = "^2.1.2"
python-jose = "^3.3.0"
cryptography = "^41.0.1"

[tool.poetry.group.dev.dependencies]
sqlalchemy2-stubs = "^0.0.2a32"
coverage = "^7.2.2"
pytest = {extras = ["asyncio"], version = "^7.2.2"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
