$schema: http://json-schema.org/draft-07/schema#
title: Settings
description: Settings for the application. Get settings from `settings.yaml` file.
type: object
properties:
  app_root_path:
    title: App Root Path
    default: ''
    type: string
  environment:
    default: development
    allOf:
    - $ref: '#/definitions/Environment'
  db_url:
    title: Db Url
    default: postgresql://postgres:postgres@localhost:5432/postgres
    type: string
    writeOnly: true
    format: password
  cors_allow_origins:
    title: Cors Allow Origins
    default:
    - https://innohassle.ru
    - https://pre.innohassle.ru
    - http://localhost:3000
    type: array
    items:
      type: string
  auth:
    $ref: '#/definitions/Authentication'
  innopolis_sso:
    $ref: '#/definitions/InnopolisSSO'
  test_user_email:
    title: Test User Email
    type: string
    format: email
  predefined_dir:
    title: Predefined Dir
    default: predefined
    type: string
    format: path
required:
- auth
definitions:
  Environment:
    title: Environment
    description: An enumeration.
    enum:
    - development
    - production
    - testing
    type: string
  Authentication:
    title: Authentication
    type: object
    properties:
      cookie_name:
        title: Cookie Name
        default: token
        type: string
      cookie_domain:
        title: Cookie Domain
        default: localhost
        type: string
      allowed_domains:
        title: Allowed Domains
        default:
        - localhost
        type: array
        items:
          type: string
      jwt_private_key:
        title: Jwt Private Key
        type: string
        writeOnly: true
        format: password
      jwt_public_key:
        title: Jwt Public Key
        type: string
      session_secret_key:
        title: Session Secret Key
        type: string
        writeOnly: true
        format: password
    required:
    - jwt_private_key
    - jwt_public_key
    - session_secret_key
  InnopolisSSO:
    title: InnopolisSSO
    description: Innopolis SSO settings (only for production)
    type: object
    properties:
      client_id:
        title: Client Id
        type: string
      client_secret:
        title: Client Secret
        type: string
        writeOnly: true
        format: password
      redirect_uri:
        title: Redirect Uri
        default: https://innohassle.campus.innopolis.university/oauth2/callback
        type: string
      resource_id:
        title: Resource Id
        type: string
    required:
    - client_id
    - client_secret
