$schema: https://json-schema.org/draft-07/schema
$defs:
  Accounts:
    additionalProperties: false
    description: InNoHassle-Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0
        title: Api Url
        type: string
      well_known_url:
        default: https://api.innohassle.ru/accounts/v0/.well-known
        title: Well Known Url
        type: string
      api_jwt_token:
        format: password
        title: Api Jwt Token
        type: string
        writeOnly: true
    required:
    - api_jwt_token
    title: Accounts
    type: object
  Environment:
    enum:
    - development
    - production
    - testing
    title: Environment
    type: string
  MusicRoom:
    additionalProperties: false
    description: InNoHassle-MusicRoom integration settings
    properties:
      api_url:
        title: Api Url
        type: string
      api_key:
        format: password
        title: Api Key
        type: string
        writeOnly: true
    required:
    - api_url
    - api_key
    title: MusicRoom
    type: object
  Sport:
    additionalProperties: false
    description: Innopolis Sport integration settings
    properties:
      api_url:
        default: https://sport.innopolis.university/api
        title: Api Url
        type: string
    title: Sport
    type: object
additionalProperties: false
description: Settings for the application. Get settings from `settings.yaml` file.
properties:
  app_root_path:
    default: ''
    title: App Root Path
    type: string
  environment:
    allOf:
    - $ref: '#/$defs/Environment'
    default: development
  db_url:
    default: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
    format: password
    title: Db Url
    type: string
    writeOnly: true
  cors_allow_origins:
    default:
    - https://innohassle.ru
    - https://pre.innohassle.ru
    - http://localhost:3000
    items:
      type: string
    title: Cors Allow Origins
    type: array
  predefined_dir:
    default: predefined
    format: path
    title: Predefined Dir
    type: string
  accounts:
    $ref: '#/$defs/Accounts'
  music_room:
    anyOf:
    - $ref: '#/$defs/MusicRoom'
    - type: 'null'
    default: null
  sport:
    anyOf:
    - $ref: '#/$defs/Sport'
    - type: 'null'
    default:
      api_url: https://sport.innopolis.university/api
  $schema:
    description: Path to the schema file
    title: Schema
    type: string
required:
- accounts
title: Settings
type: object
