$schema: http://json-schema.org/draft-07/schema#
$defs:
  Authentication:
    additionalProperties: false
    properties:
      cookie_name:
        default: token
        title: Cookie Name
        type: string
      cookie_domain:
        default: localhost
        title: Cookie Domain
        type: string
      allowed_domains:
        default:
        - localhost
        items:
          type: string
        title: Allowed Domains
        type: array
      jwt_private_key:
        format: password
        title: Jwt Private Key
        type: string
        writeOnly: true
      jwt_public_key:
        title: Jwt Public Key
        type: string
      session_secret_key:
        format: password
        title: Session Secret Key
        type: string
        writeOnly: true
    required:
    - jwt_private_key
    - jwt_public_key
    - session_secret_key
    title: Authentication
    type: object
  Environment:
    enum:
    - development
    - production
    - testing
    title: Environment
    type: string
  InnopolisSSO:
    additionalProperties: false
    description: Innopolis SSO settings (only for production)
    properties:
      client_id:
        title: Client Id
        type: string
      client_secret:
        format: password
        title: Client Secret
        type: string
        writeOnly: true
      redirect_uri:
        default: https://innohassle.campus.innopolis.university/oauth2/callback
        title: Redirect Uri
        type: string
      resource_id:
        anyOf:
        - type: string
        - type: 'null'
        default: null
        title: Resource Id
    required:
    - client_id
    - client_secret
    title: InnopolisSSO
    type: object
  MusicRoom:
    additionalProperties: false
    description: InNoHassle-MusicRoom integration settings
    properties:
      api_url:
        title: Api Url
        type: string
      api_key:
        format: password
        title: Api Key
        type: string
        writeOnly: true
    required:
    - api_url
    - api_key
    title: MusicRoom
    type: object
additionalProperties: false
description: Settings for the application. Get settings from `settings.yaml` file.
properties:
  app_root_path:
    default: ''
    title: App Root Path
    type: string
  environment:
    allOf:
    - $ref: '#/$defs/Environment'
    default: development
  db_url:
    default: postgresql://postgres:postgres@localhost:5432/postgres
    format: password
    title: Db Url
    type: string
    writeOnly: true
  cors_allow_origins:
    default:
    - https://innohassle.ru
    - https://pre.innohassle.ru
    - http://localhost:3000
    items:
      type: string
    title: Cors Allow Origins
    type: array
  auth:
    $ref: '#/$defs/Authentication'
  innopolis_sso:
    anyOf:
    - $ref: '#/$defs/InnopolisSSO'
    - type: 'null'
    default: null
  test_user_email:
    anyOf:
    - format: email
      type: string
    - type: 'null'
    default: null
    title: Test User Email
  predefined_dir:
    default: predefined
    format: path
    title: Predefined Dir
    type: string
  music_room:
    anyOf:
    - $ref: '#/$defs/MusicRoom'
    - type: 'null'
    default: null
  $schema:
    description: Path to the schema file
    title: Schema
    type: string
required:
- auth
title: Settings
type: object
