name: pytest

on: [ push, pull_request ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - run: pip install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install --only main,test
      - run: poetry run pytest
        env:
          ENVIRONMENT: 'testing'
          SESSION_SECRET_KEY: 'this is secret key'
          JWT_SECRET_KEY: 'this is another secret key'
          DB_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
