name: pytest

on: [ push, pull_request ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - run: pip install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - run: poetry install --only main,test
      - run: |
          poetry run pytest \
              --junitxml=pytest.xml \
              --cov=src \
              --cov-report=term-missing:skip-covered \
              | tee pytest-coverage.txt
        env:
          ENVIRONMENT: 'testing'
          SESSION_SECRET_KEY: 'this is secret key'
          JWT_SECRET_KEY: 'this is another secret key'
          DB_URL: 'postgresql+asyncpg://postgres:postgres@localhost:5432/postgres'
      - uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
